### ISSUE TITLE
Code modification

### ISSUE THREAD

**Issue by Elimby** [n-yousefi/Arg-Graph#2]
you code has helped me a lot thanks.
I have touched the code a bit, if you like I can send it to you.
a greeting, thank you.
I have added new sections and other things....:

"dataArrow": "false",
"style":{
            "backgroundColor": "white",
            "color":"#f06f24",
            "border": "solid 2px #f06f24"
        },

![image](https://user-images.githubusercontent.com/33656401/44911885-c5956700-ad28-11e8-9e5b-c21a366c56b3.png)

**Comment by n-yousefi** [comment]
Yes, definitely, I'll be happy if you share your enhancements with us. Feel free to send a pull request on the repo to help improve the project.  Thank you.
